<a href="https://colab.research.google.com/github/zombe962/Pythoin-Math-For-AI-100/blob/master/8.%20MNIST%EC%99%80%20%EC%8B%A0%EA%B2%BD%EB%A7%9D%EC%9D%98%20%EC%9E%85%EB%A0%A5%EA%B3%BC%20%EC%B6%9C%EB%A0%A5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 8.4 행렬계산을 위한 파이썬 코드 1
# X + Y = 1100 ......(1)
# 2X + 3Y = 2800 ......(2)
# 연립방정식을 행렬계산을 이용해 풀어보자
import numpy as np
from numpy.linalg import inv  # 이것 대신에 numpy.linalg.inv() 사용 가능

A = np.array([[1, 1],
              [2, 3]])
B = np.array([[1100],
              [2800]])

invA = inv(A) # inv는 행렬의 역행렬을 만드는 함수
print(np.dot(invA, B))

[[500.]
 [600.]]


# 8.4 행렬계산을 위한 파이썬 코드 2

from numpy.linalg import inv 대신 numpy.linalg.inv() 사용가능 하다는 내용이므로 **생략**

In [1]:
# 8.4 행렬계산을 위한 파이썬 코드 3

import numpy as np
from numpy.linalg import inv

A = np.array([[1,1,1,1],
             [5,2,4,7],
             [0,1,1,2],
             [5,2,2,3]])
B = np.array([[2350],
             [10600],
             [2450],
             [6800]])

invA = inv(A)
print(np.dot(invA, B))

[[500.]
 [550.]
 [700.]
 [600.]]


In [1]:
# 8.4 행렬계산을 위한 파이썬 코드 4

# 전치행렬(Transpose)
# 행과 열을 서로 바꾼 형태의 행렬
import numpy as np

#(1) 행렬을 만들고
A = np.array([[1,1],
              [2,3]])

print("A = \n", A)
print("A.T = \n", A.T)  # (2) 행렬이름 뒤에 .T를 붙임

A = 
 [[1 1]
 [2 3]]
A.T = 
 [[1 2]
 [1 3]]


In [6]:
# 8.6. 무작위 데이터로 신경망함수 만들기

# 00. keras에서 mnist 데이터 읽어오기
import numpy as np
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# 데이터 포맷은 60000, 28, 28 / 10000, 28,28
# 데이터를 28x28에서 784로 변경
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)

# 01 Hidden 1 Layer : W, b 초기화 [W1, W2, B1, B2]
def init_mnistbw2(layer_x, layer_h, layer_y):
  matrix_nn = {}
  matrix_nn = dict(B1 = np.random.rand(layer_h),
                   B2 = np.random.rand(layer_y),
                   W1 = np.random.rand(layer_x, layer_h),
                   W2 = np.random.rand(layer_h, layer_y))
  return matrix_nn

# 02. 활성함수
def sigmoid(x):
  return 1 / (1+np.exp(-x))

# 03. 소프트맥스
def softmax(X):
  X = X.T - np.max(X.T, axis = 0)
  return (np.exp(X) / np.sum(np.exp(X), axis = 0)).T

# 04. predict
def predict(X):
  A = sigmoid(np.dot(X, W1) + B1)
  B = sigmoid(np.dot(A, W2) + B2)
  return softmax(B)

#process

ibw = init_mnistbw2(784, 50, 10)
W1, W2, B1, B2 = ibw['W1'], ibw['W2'], ibw['B1'], ibw['B2']
accuracy = 0

for i in range(len(x_test)):  #10,000
  y = predict(x_test[i])
  p = np.argmax(y)
  if p == y_test[i]:
    accuracy = accuracy + 1

print("Acc = ", str(float(accuracy/len(x_test)))) # 0.1 근처의 값

Acc =  0.0982


학습이 되지 않았으므로 0.1 근처의 값이 나오게 된다. (1/10의 정답률)